tap "bellicose100xp/tap"
tap "boolean-maybe/tap"
tap "felixkratz/formulae"
tap "jesseduffield/lazygit"
tap "jorgerojas26/lazysql"
tap "knqyf263/pet"
tap "mediosz/tap"
tap "nikitabobko/tap"
tap "anomalyco/tap"
brew "bash"
brew "bat"
brew "btop"
brew "coreutils"
brew "curl"
brew "dotenv-linter"
brew "duf"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fnm"
brew "fx"
brew "fzf"
brew "gcc"
brew "gdu"
brew "gh"
brew "ghostscript"
brew "git"
brew "git-delta"
brew "dlvhdr/formulae/diffnav"
brew "glow"
brew "golangci-lint"
brew "grep"
brew "gum"
brew "libtool"
brew "imagemagick"
brew "jenv"
brew "jq"
brew "lazydocker"
brew "lazygit"
brew "lua"
brew "luarocks"
brew "mprocs"
brew "neovim"
brew "python"
brew "pipx"
brew "posting"
brew "presenterm"
brew "python-setuptools"
brew "python@3.14"
brew "ripgrep"
brew "brevity1swos/tap/rgx"
brew "sad"
brew "spotifyd"
brew "starship"
brew "stow"
brew "tailspin"
brew "thefuck"
brew "tlrc"
brew "tmux"
brew "tmuxinator"
brew "typos-cli"
brew "vhs"
brew "watchman"
brew "wget"
brew "yazi"
brew "yq"
brew "zoxide"
brew "bellicose100xp/tap/jiq"
brew "boolean-maybe/tap/tiki"
brew "felixkratz/formulae/borders"
brew "jorgerojas26/lazysql/lazysql"
brew "knqyf263/pet/pet"
brew "anomalyco/tap/opencode"
cask "1password-cli"
cask "nikitabobko/tap/aerospace"
cask "betterdisplay"
cask "ghostty"
cask "hiddenbar"
cask "localsend"
cask "linearmouse"
cask "ngrok"
cask "raycast"
cask "react-native-debugger"
cask "mediosz/tap/swipeaerospace"
cask "warp"
cask "wezterm"
cask "zulu@17"
mas "Amphetamine", id: 937984704
mas "Bitwarden", id: 1352778147
mas "DevCleaner", id: 1388020431
mas "Developer", id: 640199958
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Slack", id: 803453959
mas "TestFlight", id: 899247664
mas "WhatsApp", id: 310633997
mas "Xcode", id: 497799835
go "github.com/air-verse/air"
go "github.com/spf13/cobra-cli"
go "mvdan.cc/gofumpt"
go "github.com/segmentio/golines"
go "github.com/fatih/gomodifytags"
go "golang.org/x/tools/gopls"
go "github.com/cweill/gotests/gotests"
go "github.com/koron/iferr"
go "github.com/josharian/impl"
go "github.com/Gelio/go-global-update"
cargo "cargo-generate"
cargo "cargo-binstall"
cargo "cargo-update"
cargo "cargo-cache"
cargo "resvg"
cargo "selene"
cargo "spotify_player"
cargo "stylua"
