theme {
  style = Fusion
  color_scheme = $HOME/.config/qt6ct/colors/catppuccin-mocha-mauve.conf
  icon_theme = breeze-dark
  font = Lato
  font_size = 9
  font_fixed = FiraCode Nerd Font
  font_fixed_size = 9
}
