# Include any additional configuration file(s)
# [include] sections are processed in the order you write them
# Files in $CONFIG_DIR/topgrade.d/ are automatically included before this file
[include]
# paths = ["/etc/topgrade.toml"]


[misc]
# allow_root = false

pre_sudo = false

# Periodically runs `sudo -v` or `please -w` to avoid password re-prompts during updates (default: false)
# WARNING: This is a potential security risk; if you walk away from the computer while topgrade is running,
# another person can come by, CTRL+C, and gain access to a sudo session.
# sudo_loop = true
# sudo_loop_interval = 240 # 4 minutes (240s); default if sudo_loop enabled

# sudo_command = "sudo"

disable = ["microsoft_office"]

# Run these steps before all others
# first = ["chezmoi"]

# Run these steps after all others
# last = ["system"]

# ignore_failures = ["powershell"]

# Arguments to pass tmux when pulling Repositories
# tmux_arguments = "-S /var/tmux.sock"

# Do not set the terminal title (default: true)
# set_title = true

# Display the time in step titles (default: true)
display_time = false

# Don't ask for confirmations (no default value)
# assume_yes = true

# Whether to ask what to do after a step fails (default: true)
# ask_retry = true

# Number of times to automatically retry a step when it fails (default: 0)
# auto_retry = 0

# Show the reason for skipped steps (default: false)
# This has no effect if the "only" option is specified
show_skipped = false

# Run inside tmux (default: false)
# run_in_tmux = true

# Changes the way topgrade interacts with
# the tmux session, creating the session
# and only attaching to it if not inside tmux
# (default: "attach_if_not_in_session", allowed values: "attach_if_not_in_session", "attach_always")
# tmux_session_mode = "attach_if_not_in_session"

# Cleanup temporary or old files (default: false)
cleanup = true

# notify_each_step = false

# When to send a notification at the end of a run
# (default: "always", allowed values: "always", "never", "on_failure")
notify_end = "always"

# The Bash-it branch to update (default: "stable")
# bashit_branch = "stable"

# Run specific steps - same options as the command line flag
# only = ["system", "emacs"]

# Whether to self update
#
# this will be ignored if the binary is built without self update support
#
# available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
# no_self_update = true

# Extra tracing filter directives
# These are prepended to the `--log-filter` argument
# See: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
# log_filters = ["topgrade::command=debug", "warn"]

# Whether to show a distribution-specific summary if applicable, e.g. listing
# Pacman backup configuration files (*.pacsave and *.pacnew)
# (default: true)
# show_distribution_summary = false

# For NixOS/home-manager, there are multiple ways to switch to newer configurations.
# When set to autodetect: use nh when available, fall back to vanilla
# Allowed values:
#   autodetect, nh, vanilla
# nix_handler = "autodetect"


# Commands to run before anything
[pre_commands]
# "Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Commands to run after anything
[post_commands]
"tmux plugins" = "~/.config/tmux/plugins/tpm/bin/update_plugins all"
"Clear evalcache" = "clear_evalcache"
# "Generate zsh completions" = "generate_zsh_completions"
"Compile zsh configurations" = "compile_zsh_configs"

# Custom commands
[commands]
"tmux plugins" = "~/.config/tmux/plugins/tpm/bin/update_plugins all"

[python]
# enable_pip_review = true                         ###disabled by default
# enable_pip_review_local = true                   ###disabled by default
enable_pipupgrade = true ###disabled by default
# pipupgrade_arguments = "-y -u --pip-path pip"    ###disabled by default

# For the poetry step, by default, Topgrade skips its update if poetry is not
# installed with the official script. This configuration entry forces Topgrade
# to run the update in this case.
#
# (default: false)
# poetry_force_self_update = true

[brew]
# For the BrewCask step
# If `Repo Cask Upgrade` exists, then use the `-a` option.
# Otherwise, use the `--greedy` option.
# greedy_cask = true

# For the BrewCask step
# If `Repo Cask Upgrade` does not exist, then use the `--greedy_latest` option.
# NOTE: the above entry `greedy_cask` contains this entry, though you can enable
# both of them, they won't clash with each other.
# greedy_latest = true

# For the BrewCask step
# If `Repo Cask Upgrade` does not exist, then use the `--greedy_auto_updates` option.
# NOTE: the above entry `greedy_cask` contains this entry, though you can enable
# both of them, they won't clash with each other.
# greedy_auto_updates = true

# For the BrewFormula step
# Execute `brew autoremove` after the step.
autoremove = true

# For the BrewFormula step
# Upgrade formulae built from the HEAD branch; `brew upgrade --fetch-HEAD`
# fetch_head = true


[linux]
# Arch Package Manager to use.
# Allowed values:
#   autodetect, aura, garuda_update, pacman, pamac, paru, pikaur, shelly, trizen, yay
arch_package_manager = "yay"

# Arguments to pass yay (or paru) when updating packages
# yay_arguments = "--nodevel"

# Arguments to pass dnf when updating packages
# dnf_arguments = "--refresh"
# aura_aur_arguments = "-kx"
# aura_pacman_arguments = ""
# garuda_update_arguments = ""
# show_arch_news = true
# trizen_arguments = "--devel"
# pikaur_arguments = ""
# pamac_arguments = "--no-devel"
# shelly_arguments = ""
# enable_tlmgr = true
# emerge_sync_flags = "-q"
# emerge_update_flags = "-uDNa --with-bdeps=y world"
# redhat_distro_sync = false
# suse_dup = false
# rpm_ostree = false
# For Fedora/CentOS/RHEL Atomic variants, if `bootc` is available and this configuration entry is set to true, use
# it to do the update - Will also supersede rpm-ostree if enabled
# (default: false)
# bootc = false
# nix_arguments = "--flake"
# nix_env_arguments = "--prebuilt-only"
# Extra Home Manager arguments
# home_manager_arguments = ["--flake", "file"]

[git]
# How many repos to pull or fetch at max in parallel
# max_concurrency = 5

# Additional git repositories to pull or fetch
repos = ["~/src/*", "~/Developer/**"]

# Set to `false` to skip pulling/fetching the predefined git repos
# pull_predefined = false

# Arguments to pass Git when pulling/fetching Repositories
# arguments = "--rebase --autostash"

# Whether to perform a `git fetch` instead of `git pull`
# fetch_only = false

[chezmoi]
# Exclude encrypted files from update
# (default: false)
# exclude_encrypted = false

[npm]
# use_sudo = true

# [viteplus]
# Use sudo if the Vite+ directory isn't owned by the current user
# use_sudo = true

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = false

[containers]
# Specify the containers to ignore while updating (Wildcard supported)
# ignored_containers = ["ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest", "docker.io*"]
# Specify the runtime to use for containers (default: "docker", allowed values: "docker", "podman")
# runtime = "podman"

# Run 'docker system prune' to clean up unused containers, networks, and build cache
# (default: false)
# system_prune = false

# Use sudo for updating containers. Necessary for non-rootless installs.
# (default: false)
# use_sudo = false

[vscode]
# If this is set and is a non-empty string, it specifies the profile the
# extensions should be updated for.
# (default: this won't be set by default)
# profile = ""

[cargo]
# If this is set to true, `cargo install-update` also updates git-originating packages.
# (default: true)
# git = false

# If this is set to true, `cargo install-update` is run quietly.
# (default: false)
# quiet = true

# Other options like `--locked` or `--jobs` can be passed to `cargo install`
# using the `CARGO_INSTALL_OPTS` environment variable.

[rustup]
# If set, updates only these channels.
# (default: [] (all channels))
# channels = ["stable"]
