# Include any additional configuration file(s)
# [include] sections are processed in the order you write them
# Files in $CONFIG_DIR/topgrade.d/ are automatically included before this file
[include]
# paths = ["/etc/topgrade.toml"]


[misc]
# allow_root = false
pre_sudo = false

# Periodically runs `sudo -v` or `please -w` to avoid password re-prompts during updates (default: false)
# WARNING: This is a potential security risk; if you walk away from the computer while topgrade is running,
# another person can come by, CTRL+C, and gain access to a sudo session.
# sudo_loop = true
# sudo_loop_interval = 240 # 4 minutes (240s); default if sudo_loop enabled

# sudo_command = "sudo"
disable = ["microsoft_office"]
first = ["git_repos"]
# last = ["system"]
# ignore_failures = ["powershell"]
# tmux_arguments = "-S /var/tmux.sock"
# set_title = true
display_time = false

# Don't ask for confirmations (no default value)
# assume_yes = true

# Whether to ask what to do after a step fails (default: true)
# ask_retry = true

# auto_retry = 0
show_skipped = false
# run_in_tmux = false

# Changes the way topgrade interacts with
# the tmux session, creating the session
# and only attaching to it if not inside tmux
# (default: "attach_if_not_in_session", allowed values: "attach_if_not_in_session", "attach_always")
# tmux_session_mode = "attach_if_not_in_session"

cleanup = true
# notify_each_step = false

# When to send a notification at the end of a run
# (default: "always", allowed values: "always", "never", "on_failure")
notify_end = "always"

# The Bash-it branch to update (default: "stable")
# bashit_branch = "stable"

# only = ["system", "emacs"]

# Whether to self update
#
# this will be ignored if the binary is built without self update support
#
# available also via setting the environment variable TOPGRADE_NO_SELF_UPGRADE)
# no_self_update = true

# Extra tracing filter directives
# These are prepended to the `--log-filter` argument
# See: https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives
# log_filters = ["topgrade::command=debug", "warn"]

# Whether to show a distribution-specific summary if applicable, e.g. listing
# Pacman backup configuration files (*.pacsave and *.pacnew)
# (default: true)
# show_distribution_summary = false

# For NixOS/home-manager, there are multiple ways to switch to newer configurations.
# When set to autodetect: use nh when available, fall back to vanilla
# Allowed values:
#   autodetect, nh, vanilla
# nix_handler = "autodetect"


# Commands to run before anything
[pre_commands]
# "Emacs Snapshot" = "rm -rf ~/.emacs.d/elpa.bak && cp -rl ~/.emacs.d/elpa ~/.emacs.d/elpa.bak"

# Commands to run after anything
[post_commands]

# Custom commands
[commands]
"tmux plugins" = "~/.config/tmux/plugins/tpm/bin/update_plugins all"
"Clear evalcache" = "zsh -ic clear_evalcache"
"Compile zsh configurations" = "zsh -ic compile_zsh_configs"

[python]
# enable_pip_review = true                         ###disabled by default
# enable_pip_review_local = true                   ###disabled by default
enable_pipupgrade = true ###disabled by default
# pipupgrade_arguments = "-y -u --pip-path pip"    ###disabled by default
# poetry_force_self_update = true

[brew]
# For the BrewCask step
# If `Repo Cask Upgrade` exists, then use the `-a` option.
# Otherwise, use the `--greedy` option.
# greedy_cask = true

# For the BrewCask step
# If `Repo Cask Upgrade` does not exist, then use the `--greedy_latest` option.
# NOTE: the above entry `greedy_cask` contains this entry, though you can enable
# both of them, they won't clash with each other.
# greedy_latest = true

# For the BrewCask step
# If `Repo Cask Upgrade` does not exist, then use the `--greedy_auto_updates` option.
# NOTE: the above entry `greedy_cask` contains this entry, though you can enable
# both of them, they won't clash with each other.
# greedy_auto_updates = true

autoremove = true
# fetch_head = true

[linux]
arch_package_manager = "yay"
# yay_arguments = "--nodevel"

# enable_tlmgr = true
# emerge_sync_flags = "-q"
# emerge_update_flags = "-uDNa --with-bdeps=y world"
# home_manager_arguments = ["--flake", "file"]

[git]
# max_concurrency = 5
repos = ["~/dotfiles", "~/.config/nvim", "~/src/*", "~/Developer/**"]

# Set to `false` to skip pulling/fetching the predefined git repos
# pull_predefined = false
# arguments = "--rebase --autostash"

# fetch_only = false

[chezmoi]
# Exclude encrypted files from update
# (default: false)
# exclude_encrypted = false

[npm]
# use_sudo = true

# [viteplus]
# Use sudo if the Vite+ directory isn't owned by the current user
# use_sudo = true

[firmware]
# Offer to update firmware; if false just check for and display available updates
upgrade = false

[containers]
# ignored_containers = ["ghcr.io/rancher-sandbox/rancher-desktop/rdx-proxy:latest", "docker.io*"]
# runtime = "docker"
system_prune = true
# use_sudo = false

[vscode]
# profile = ""

[cargo]
# If this is set to true, `cargo install-update` also updates git-originating packages.
# (default: true)
# git = false

# quiet = false

[rustup]
# channels = ["stable"]
